services:
  app:
    build: .
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: jail_vms
    ports:
      - "3306:3306"